name: "Set up ccache-ghac-adapter"
description: "Installs and configures ccache and ccache-ghac-adapter"

inputs:
  adapter-port:
    description: "Port for ccache-ghac-adapter to listen on"
    required: false
    default: "3459"
  namespace:
    description: "Cache namespace"
    required: false
    default: "ccache"
  github-token:
    description: "GitHub token for accessing the Actions cache"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Get latest ccache release"
      uses: actions/github-script@v8
      id: get_ccache_release
      with:
        script: |
          const response = await github.rest.repos.getLatestRelease({
            owner: 'ccache',
            repo: 'ccache',
          });
          core.setOutput('tag_name', response.data.tag_name);

    - name: "Install ccache"
      shell: bash
      env:
        CCACHE_TAG: ${{ steps.get_ccache_release.outputs.tag_name }}
      run: |
        # Download from GitHub releases
        case "$RUNNER_OS $RUNNER_ARCH" in
          "Linux X64")
            FILE_NAME="ccache-${CCACHE_TAG#v}-linux-x86_64"
            EXTENSION="tar.xz"
            ;;
          "Linux ARM64")
            FILE_NAME="ccache-${CCACHE_TAG#v}-linux-aarch64"
            EXTENSION="tar.xz"
            ;;
          "macOS ARM64")
            FILE_NAME="ccache-${CCACHE_TAG#v}-darwin"
            EXTENSION="tar.gz"
            ;;
          "Windows X64")
            FILE_NAME="ccache-${CCACHE_TAG#v}-windows-x86_64"
            EXTENSION="zip"
            ;;
          "Windows ARM64")
            FILE_NAME="ccache-${CCACHE_TAG#v}-windows-aarch64"
            EXTENSION="zip"
            ;;
          *)
            echo "Unsupported OS/Architecture combination: $RUNNER_OS/$RUNNER_ARCH"
            exit 1
            ;;
        esac

        TMP_DIR="$RUNNER_TEMP"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          TMP_DIR="$(cygpath $RUNNER_TEMP)"
        fi

        CCACHE_URL="https://github.com/ccache/ccache/releases/download/${CCACHE_TAG}/${FILE_NAME}.${EXTENSION}"
        CCACHE_DIR="$TMP_DIR/ccache"
        mkdir -p "$CCACHE_DIR"
        curl -L "$CCACHE_URL" -o "$CCACHE_DIR/$FILE_NAME.$EXTENSION"
        if [[ "$EXTENSION" == "zip" ]]; then
          unzip "$CCACHE_DIR/$FILE_NAME.$EXTENSION" -d "$CCACHE_DIR"
        else
          tar -xf "$CCACHE_DIR/$FILE_NAME.$EXTENSION" -C "$CCACHE_DIR"
        fi
        rm "$CCACHE_DIR/$FILE_NAME.$EXTENSION"

        export PATH="$CCACHE_DIR/$FILE_NAME:$PATH"
        echo "$CCACHE_DIR/$FILE_NAME" >> $GITHUB_PATH

        ccache --version

    - name: "Get latest ccache-ghac-adapter release"
      uses: actions/github-script@v8
      id: get_adapter_release
      with:
        script: |
          const response = await github.rest.repos.getLatestRelease({
            owner: 'cbjeukendrup',
            repo: 'ccache-ghac-adapter',
          });
          core.setOutput('tag_name', response.data.tag_name);

    - name: "Install ccache-ghac-adapter"
      shell: bash
      env:
        ADAPTER_TAG: ${{ steps.get_adapter_release.outputs.tag_name }}
      run: |
        # Download from GitHub releases
        case "$RUNNER_OS $RUNNER_ARCH" in
          "Linux X64")
            FILE_NAME="ccache-ghac-adapter-${ADAPTER_TAG}-linux-x86_64.tar.gz"
            ;;
          "Linux ARM64")
            FILE_NAME="ccache-ghac-adapter-${ADAPTER_TAG}-linux-aarch64.tar.gz"
            ;;
          "macOS ARM64")
            FILE_NAME="ccache-ghac-adapter-${ADAPTER_TAG}-macos-aarch64.tar.gz"
            ;;
          "Windows X64")
            FILE_NAME="ccache-ghac-adapter-${ADAPTER_TAG}-windows-x86_64.tar.gz"
            ;;
          *)
            echo "Unsupported OS/Architecture combination: $RUNNER_OS/$RUNNER_ARCH"
            exit 1
            ;;
        esac

        TMP_DIR="$RUNNER_TEMP"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          TMP_DIR="$(cygpath $RUNNER_TEMP)"
        fi

        ADAPTER_URL="https://github.com/cbjeukendrup/ccache-ghac-adapter/releases/download/${ADAPTER_TAG}/${FILE_NAME}"
        ADAPTER_DIR="$TMP_DIR/ccache-ghac-adapter"
        mkdir -p "$ADAPTER_DIR"
        curl -L "$ADAPTER_URL" -o "$ADAPTER_DIR/$FILE_NAME"
        tar -xf "$ADAPTER_DIR/$FILE_NAME" -C "$ADAPTER_DIR"
        rm "$ADAPTER_DIR/$FILE_NAME"

        export PATH="$ADAPTER_DIR:$PATH"
        echo "$ADAPTER_DIR" >> $GITHUB_PATH

        ccache-ghac-adapter --version

    - name: "Configure ccache to use ccache-ghac-adapter"
      shell: bash
      env:
        CCACHE_GHAC_ADAPTER_PORT: ${{ inputs.adapter-port }}
        CCACHE_GHAC_NAMESPACE: ${{ inputs.namespace }}
      run: |
        echo "CCACHE_REMOTE_ONLY=true" >> $GITHUB_ENV
        echo "CCACHE_REMOTE_STORAGE=http://localhost:$CCACHE_GHAC_ADAPTER_PORT" >> $GITHUB_ENV

    - name: Prepare environment for ccache-ghac-adapter
      uses: actions/github-script@v8
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Start ccache-ghac-adapter
      uses: JarvusInnovations/background-action@v1
      env:
        CCACHE_GHAC_ADAPTER_PORT: ${{ inputs.adapter-port }}
        CCACHE_GHAC_NAMESPACE: ${{ inputs.namespace }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        run: ccache-ghac-adapter --port $CCACHE_GHAC_ADAPTER_PORT --namespace $CCACHE_GHAC_NAMESPACE &
        wait-on: http://localhost:${{ env.CCACHE_GHAC_ADAPTER_PORT }}
        wait-for: 10s
